using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MovieApplication.Models.Entities;

namespace MovieApplication.Database.Configurations
{
    public class MovieConfiguration : IEntityTypeConfiguration<Movie>
    {
        public void Configure(EntityTypeBuilder<Movie> builder)
        {

            builder.HasOne<Director>(d => d.Director)
                .WithMany(d => d.Movies)
                .HasForeignKey(d => d.DirectorId);

            builder.HasOne<Genre>(g => g.Genre)
                .WithMany(g => g.Movies)
                .HasForeignKey(g => g.GenreId);


            

            //SEEDING MOVIES

            builder.HasData(
             new Movie() { MovieId = 1, DirectorId = 1, GenreId = 1, Title = "Titanic", Duration = 194, PhotoUrl = "https://m.media-amazon.com/images/M/MV5BMDdmZGU3NDQtY2E5My00ZTliLWIzOTUtMTY4ZGI1YjdiNjk3XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_UX182_CR0,0,182,268_AL_.jpg", Price = 9.8, ProductionYear = new DateTime(1997, 1, 1), Rating = 7.8D, TrailerUrl = "https://www.youtube.com/watch?v=b0KYvGa_nN8", Watched = false, Country = Country.United_States_of_America },
             new Movie() { MovieId = 2, DirectorId = 3, GenreId = 3, Title = "Inception", Duration = 148, PhotoUrl = "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_UX182_CR0,0,182,268_AL_.jpg", Price = 16, ProductionYear = new DateTime(2010, 1, 1), Rating = 8.8D, TrailerUrl = "https://www.youtube.com/watch?v=YoHD9XEInc0", Watched = false, Country = Country.United_States_of_America },
             new Movie() { MovieId = 3, DirectorId = 2, GenreId = 2, Title = "Once Upon a Time... in Hollywood", Duration = 161, PhotoUrl = "https://m.media-amazon.com/images/M/MV5BOTg4ZTNkZmUtMzNlZi00YmFjLTk1MmUtNWQwNTM0YjcyNTNkXkEyXkFqcGdeQXVyNjg2NjQwMDQ@._V1_UX182_CR0,0,182,268_AL_.jpg", Price = 7.7, ProductionYear = new DateTime(2019, 1, 1), Rating = 7.7D, TrailerUrl = "https://www.youtube.com/watch?v=ELeMaP8EPAA", Watched = false, Country = Country.United_States_of_America },
             new Movie() { MovieId = 4, DirectorId = 1, GenreId = 3, Title = "Avatar", Duration = 162, PhotoUrl = "https://m.media-amazon.com/images/M/MV5BMTYwOTEwNjAzMl5BMl5BanBnXkFtZTcwODc5MTUwMw@@._V1_UX182_CR0,0,182,268_AL_.jpg", Price = 13.5, ProductionYear = new DateTime(2009, 1, 1), Rating = 7.8D, TrailerUrl = "https://www.youtube.com/watch?v=6ziBFh3V1aM", Watched = false, Country = Country.United_States_of_America },
             new Movie() { MovieId = 5, DirectorId = 1, GenreId = 4, Title = "The Abyss", Duration = 171, PhotoUrl = "https://m.media-amazon.com/images/M/MV5BYWMzMDNlMDQtMTYyYi00OTM3LTllZDYtYThhMTk5MzNhZTRhXkEyXkFqcGdeQXVyMDUyOTUyNQ@@._V1_UX182_CR0,0,182,268_AL_.jpg", Price = 13, ProductionYear = new DateTime(1989, 1, 1), Rating = 7.6D, TrailerUrl = "https://www.youtube.com/watch?v=4zbpL3LeW7k", Watched = false, Country = Country.United_States_of_America },
             new Movie() { MovieId = 6, DirectorId = 4, GenreId = 3, Title = "The Rock", Duration = 136, PhotoUrl = "https://m.media-amazon.com/images/M/MV5BZDJjOTE0N2EtMmRlZS00NzU0LWE0ZWQtM2Q3MWMxNjcwZjBhXkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_UX182_CR0,0,182,268_AL_.jpg", Price = 13, ProductionYear = new DateTime(1996, 1, 1), Rating = 7.6D, TrailerUrl = "https://www.youtube.com/watch?v=313n0wga2xo", Watched = false, Country = Country.United_States_of_America },
             new Movie() { MovieId = 7, DirectorId = 5, GenreId = 5, Title = "Der Name der Rose", Duration = 170, PhotoUrl = "https://m.media-amazon.com/images/M/MV5BZjEyZTdhNDMtMWFkMS00ZmRjLWEyNmEtZDU3MWFkNDEzMDYwXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_UX182_CR0,0,182,268_AL_.jpg", Price = 18, ProductionYear = new DateTime(1986, 1, 1), Rating = 7.6D, TrailerUrl = "https://www.youtube.com/watch?v=wrWpJkWPVNI", Watched = false, Country = Country.United_States_of_America },
             new Movie() { MovieId = 8, DirectorId = 6, GenreId = 6, Title = "Snowden", Duration = 134, PhotoUrl = "https://m.media-amazon.com/images/M/MV5BMTg2MzYzNzgzOF5BMl5BanBnXkFtZTgwOTg4NzQ4OTE@._V1_UX182_CR0,0,182,268_AL_.jpg", Price = 10, ProductionYear = new DateTime(2016, 1, 1), Rating = 7.3D, TrailerUrl = "https://www.youtube.com/watch?v=QlSAiI3xMh4", Watched = false, Country = Country.United_States_of_America },
             new Movie() { MovieId = 9, DirectorId = 7, GenreId = 3, Title = "Season of the Witch", Duration = 95, PhotoUrl = "https://m.media-amazon.com/images/M/MV5BMzc3MjYxNzg2N15BMl5BanBnXkFtZTcwNzQyMTkwNA@@._V1_UX182_CR0,0,182,268_AL_.jpg", Price = 9, ProductionYear = new DateTime(2011, 1, 1), Rating = 5.4D, TrailerUrl = "https://www.youtube.com/watch?v=PE6QUf1b-Xw", Watched = false, Country = Country.United_States_of_America },
             new Movie() { MovieId = 10, DirectorId = 8, GenreId = 7, Title = "The Wicker Man", Duration = 102, PhotoUrl = "https://m.media-amazon.com/images/M/MV5BOGQwN2UyM2YtNzNhOC00YjU5LWI0ZDgtZjMxZjM5ZmI0YjRmXkEyXkFqcGdeQXVyMTMxMTY0OTQ@._V1_UY268_CR1,0,182,268_AL_.jpg", Price = 8, ProductionYear = new DateTime(2006, 1, 1), Rating = 3.7D, TrailerUrl = "https://www.youtube.com/watch?v=QITzuunu-SU", Watched = false, Country = Country.United_States_of_America },
             new Movie() { MovieId = 11, DirectorId = 9, GenreId = 1, Title = "Captain Corelli's Mandolin", Duration = 131, PhotoUrl = "https://m.media-amazon.com/images/M/MV5BMjEwMzE5ODcyMF5BMl5BanBnXkFtZTcwODQ1NjEyMQ@@._V1_UY268_CR1,0,182,268_AL_.jpg", Price = 7, ProductionYear = new DateTime(2001, 1, 1), Rating = 5.9D, TrailerUrl = "https://www.youtube.com/watch?v=xjjGrxipPGQ", Watched = false, Country = Country.United_States_of_America },
             new Movie() { MovieId = 12, DirectorId = 10, GenreId = 3, Title = "Pirates of the Caribbean: On Stranger Tides", Duration = 136, PhotoUrl = "https://m.media-amazon.com/images/M/MV5BMjE5MjkwODI3Nl5BMl5BanBnXkFtZTcwNjcwMDk4NA@@._V1_UX182_CR0,0,182,268_AL_.jpg", Price = 5, ProductionYear = new DateTime(2011, 1, 1), Rating = 6.6D, TrailerUrl = "https://www.youtube.com/watch?v=0BXCVe8Yww4", Watched = false, Country = Country.United_States_of_America },
             new Movie() { MovieId = 13, DirectorId = 11, GenreId = 4, Title = "Fantastic Beasts and Where to Find Them", Duration = 174, PhotoUrl = "https://m.media-amazon.com/images/M/MV5BYWVlMDI5N2UtZTIyMC00NjZkLWI5Y2QtODM5NGE5MzA0NmVjXkEyXkFqcGdeQXVyNzU3NjUxMzE@._V1_UX182_CR0,0,182,268_AL_.jpg", Price = 12, ProductionYear = new DateTime(2018, 1, 1), Rating = 6.6D, TrailerUrl = "https://www.youtube.com/watch?v=vvFybpmyB9E", Watched = false, Country = Country.United_States_of_America },
             new Movie() { MovieId = 14, DirectorId = 10, GenreId = 4, Title = "Into the Woods", Duration = 165, PhotoUrl = "https://m.media-amazon.com/images/M/MV5BMTY4MzQ4OTY3NF5BMl5BanBnXkFtZTgwNjM5MDI3MjE@._V1_UX182_CR0,0,182,268_AL_.jpg", Price = 11, ProductionYear = new DateTime(2014, 1, 1), Rating = 5.9D, TrailerUrl = "https://www.youtube.com/watch?v=7pjy5MK1X70", Watched = false, Country = Country.United_States_of_America },
             new Movie() { MovieId = 15, DirectorId = 12, GenreId = 2, Title = "Tusk", Duration = 102, PhotoUrl = "https://m.media-amazon.com/images/M/MV5BNmQyMmUzMmYtMTA4OS00ZmRjLWE0NWYtNjc0ZGM0N2E4YzQ5XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX182_CR0,0,182,268_AL_.jpg", Price = 6, ProductionYear = new DateTime(2014, 1, 1), Rating = 5.3D, TrailerUrl = "https://www.youtube.com/watch?v=BCQJnOn0ru0", Watched = false, Country = Country.United_States_of_America },
             new Movie() { MovieId = 16, DirectorId = 13, GenreId = 3, Title = "The Tourist", Duration = 103, PhotoUrl = "https://m.media-amazon.com/images/M/MV5BMTMyMzc3OTkwMV5BMl5BanBnXkFtZTcwMjc0MTgwNA@@._V1_UX182_CR0,0,182,268_AL_.jpg", Price = 8, ProductionYear = new DateTime(2010, 1, 1), Rating = 6.0D, TrailerUrl = "https://www.youtube.com/watch?v=5XtbLezJtMg", Watched = false, Country = Country.United_States_of_America },
             new Movie() { MovieId = 17, DirectorId = 14, GenreId = 1, Title = "Sweeney Todd: The Demon Barber of Fleet Street", Duration = 116, PhotoUrl = "https://m.media-amazon.com/images/M/MV5BMTg3NjUxMzM5NV5BMl5BanBnXkFtZTcwMzQ1NjQzMw@@._V1_UX182_CR0,0,182,268_AL_.jpg", Price = 9.5, ProductionYear = new DateTime(2007, 1, 1), Rating = 7.3D, TrailerUrl = "https://www.youtube.com/watch?v=_4R72KROZ20", Watched = false, Country = Country.United_States_of_America },
             new Movie() { MovieId = 18, DirectorId = 14, GenreId = 1, Title = "Edward Scissorhands", Duration = 105, PhotoUrl = "https://m.media-amazon.com/images/M/MV5BNDUxN2I5NDUtZjdlMC00NjlmLTg0OTQtNjk0NjAxZjFmZTUzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX182_CR0,0,182,268_AL_.jpg", Price = 12.5, ProductionYear = new DateTime(1990, 1, 1), Rating = 7.9D, TrailerUrl = "https://www.youtube.com/watch?v=TBHIO60whNw", Watched = false, Country = Country.United_States_of_America },
             new Movie() { MovieId = 19, DirectorId = 15, GenreId = 3, Title = "Maleficent", Duration = 119, PhotoUrl = "https://m.media-amazon.com/images/M/MV5BZjJiYTExOTAtNWU0Yi00NzJjLTkwOTgtOTU2NWM1ZjJmYWVhXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX182_CR0,0,182,268_AL_.jpg", Price = 11.5, ProductionYear = new DateTime(2019, 1, 1), Rating = 6.7D, TrailerUrl = "https://www.youtube.com/watch?v=n0OFH4xpPr4", Watched = false, Country = Country.United_States_of_America },
             new Movie() { MovieId = 20, DirectorId = 16, GenreId = 6, Title = "Girl, Interrupted", Duration = 127, PhotoUrl = "https://m.media-amazon.com/images/M/MV5BNzdjZDYwM2QtMGNlZS00MGQzLTlhMjctYTU4NWI5MWJlYmQwXkEyXkFqcGdeQXVyMTAwMzUyOTc@._V1_UX182_CR0,0,182,268_AL_.jpg", Price = 10.5, ProductionYear = new DateTime(1999, 1, 1), Rating = 7.3D, TrailerUrl = "https://www.youtube.com/watch?v=5BHHUBZf7y4", Watched = false, Country = Country.United_States_of_America },
             new Movie() { MovieId = 21, DirectorId = 17, GenreId = 6, Title = "Changeling", Duration = 141, PhotoUrl = "https://m.media-amazon.com/images/M/MV5BOTA1Mzg3NjIxNV5BMl5BanBnXkFtZTcwNzU2NTc5MQ@@._V1_UX182_CR0,0,182,268_AL_.jpg", Price = 8.5, ProductionYear = new DateTime(2008, 1, 1), Rating = 7.7D, TrailerUrl = "https://www.youtube.com/watch?v=PmfjureC-5I", Watched = false, Country = Country.United_States_of_America },
             new Movie() { MovieId = 22, DirectorId = 19, GenreId = 3, Title = "Salt", Duration = 100, PhotoUrl = "https://m.media-amazon.com/images/M/MV5BMjIyODA2NDg4NV5BMl5BanBnXkFtZTcwMjg4NDAwMw@@._V1_UX182_CR0,0,182,268_AL_.jpg", Price = 11, ProductionYear = new DateTime(2010, 1, 1), Rating = 6.4D, TrailerUrl = "https://www.youtube.com/watch?v=QZ40WlshNwU", Watched = false, Country = Country.United_States_of_America },
             new Movie() { MovieId = 23, DirectorId = 19, GenreId = 1, Title = "Les Misérables", Duration = 158, PhotoUrl = "https://m.media-amazon.com/images/M/MV5BMTQ4NDI3NDg4M15BMl5BanBnXkFtZTcwMjY5OTI1OA@@._V1_UX182_CR0,0,182,268_AL_.jpg", Price = 12, ProductionYear = new DateTime(2012, 1, 1), Rating = 7.6D, TrailerUrl = "https://www.youtube.com/watch?v=YmvHzCLP6ug", Watched = false, Country = Country.United_States_of_America },
             new Movie() { MovieId = 24, DirectorId = 20, GenreId = 6, Title = "The Danish Girl", Duration = 119, PhotoUrl = "https://m.media-amazon.com/images/M/MV5BMjA0NjA4NjE2Nl5BMl5BanBnXkFtZTgwNzIxNTY2NjE@._V1_UX182_CR0,0,182,268_AL_.jpg", Price = 14, ProductionYear = new DateTime(2015, 1, 1), Rating = 7.1D, TrailerUrl = "https://www.youtube.com/watch?v=d88APYIGkjk", Watched = false, Country = Country.United_States_of_America },
             new Movie() { MovieId = 25, DirectorId = 21, GenreId = 6, Title = "The Theory of Everything", Duration = 163, PhotoUrl = "https://m.media-amazon.com/images/M/MV5BMTAwMTU4MDA3NDNeQTJeQWpwZ15BbWU4MDk4NTMxNTIx._V1_UX182_CR0,0,182,268_AL_.jpg", Price = 16.5, ProductionYear = new DateTime(2014, 1, 1), Rating = 7.7D, TrailerUrl = "https://www.youtube.com/watch?v=Salz7uGp72c", Watched = false, Country = Country.United_States_of_America },
             new Movie() { MovieId = 26, DirectorId = 21, GenreId = 5, Title = "On the Waterfront", Duration = 108, PhotoUrl = "https://m.media-amazon.com/images/M/MV5BY2I0MWFiZDMtNWQyYy00Njk5LTk3MDktZjZjNTNmZmVkYjkxXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_UX182_CR0,0,182,268_AL_.jpg", Price = 18.5, ProductionYear = new DateTime(1954, 1, 1), Rating = 8.1D, TrailerUrl = "https://www.youtube.com/watch?v=QOLHbQjtSFs", Watched = false, Country = Country.United_States_of_America },
             new Movie() { MovieId = 27, DirectorId = 22, GenreId = 1, Title = "East of Eden", Duration = 118, PhotoUrl = "https://m.media-amazon.com/images/M/MV5BNTYzNjI3MWUtZjg3Yi00ZDBkLWIwM2YtYmUyZGZjN2RiZjI5XkEyXkFqcGdeQXVyMDI2NDg0NQ@@._V1_UX182_CR0,0,182,268_AL_.jpg", Price = 13.5, ProductionYear = new DateTime(1955, 1, 1), Rating = 7.9D, TrailerUrl = "https://www.youtube.com/watch?v=IqVoIQ5UsT8", Watched = false, Country = Country.United_States_of_America },
             new Movie() { MovieId = 28, DirectorId = 23, GenreId = 1, Title = "Rebel Without a Cause", Duration = 111, PhotoUrl = "https://m.media-amazon.com/images/M/MV5BMjMwNWIwYzAtMWVhZi00YzQ2LTlmNGYtOTg3NDdkNTRjOWI2XkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_UX182_CR0,0,182,268_AL_.jpg", Price = 12.5, ProductionYear = new DateTime(1955, 1, 1), Rating = 7.7D, TrailerUrl = "https://www.youtube.com/watch?v=wXRgAXU1-T4", Watched = false, Country = Country.United_States_of_America },
             new Movie() { MovieId = 29, DirectorId = 24, GenreId = 2, Title = "Breakfast at Tiffany's", Duration = 105, PhotoUrl = "https://m.media-amazon.com/images/M/MV5BNGEwMTRmZTQtMDY4Ni00MTliLTk5ZmMtOWMxYWMyMTllMDg0L2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_UX182_CR0,0,182,268_AL_.jpg", Price = 11.5, ProductionYear = new DateTime(1961, 1, 1), Rating = 7.7D, TrailerUrl = "https://www.youtube.com/watch?v=-XcLVQCDtbM", Watched = false, Country = Country.United_States_of_America },
             new Movie() { MovieId = 30, DirectorId = 25, GenreId = 2, Title = "Charade", Duration = 18, PhotoUrl = "https://m.media-amazon.com/images/M/MV5BMTA0Y2UyMDUtZGZiOS00ZmVkLTg3NmItODQyNTY1ZjU1MWE4L2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_UX182_CR0,0,182,268_AL_.jpg", Price = 7, ProductionYear = new DateTime(1963, 1, 1), Rating = 7.9D, TrailerUrl = "https://www.youtube.com/watch?v=C6T2Q4XO7uA", Watched = false, Country = Country.United_States_of_America },
             new Movie() { MovieId = 31, DirectorId = 23, GenreId = 2, Title = "Being There", Duration = 110, PhotoUrl = "https://m.media-amazon.com/images/M/MV5BY2JkZTcxYjEtNmUwNi00MjIzLWE1YjUtMDYzNWJjYWQwMzA5XkEyXkFqcGdeQXVyNzM0MTUwNTY@._V1_UX182_CR0,0,182,268_AL_.jpg", Price = 6, ProductionYear = new DateTime(1979, 1, 1), Rating = 8.0D, TrailerUrl = "https://www.youtube.com/watch?v=oOOghKacg40", Watched = false, Country = Country.United_States_of_America },
             new Movie() { MovieId = 32, DirectorId = 26, GenreId = 2, Title = "The Pink Panther Strikes Again", Duration = 103, PhotoUrl = "https://m.media-amazon.com/images/M/MV5BZjhiNDU3NDEtNzFlMC00NTU2LThlMGMtNTA1ODJkNjIxN2RjXkEyXkFqcGdeQXVyMjI4MjA5MzA@._V1_UX182_CR0,0,182,268_AL_.jpg", Price = 9, ProductionYear = new DateTime(1976, 1, 1), Rating = 7.2D, TrailerUrl = "https://www.youtube.com/watch?v=VVnX-cPXpFA", Watched = false, Country = Country.United_States_of_America },
             new Movie() { MovieId = 33, DirectorId = 27, GenreId = 2, Title = "Sissi", Duration = 102, PhotoUrl = "https://m.media-amazon.com/images/M/MV5BMjdhNTBjMmMtZmVlNi00NWRhLWEwNjItM2ZjYzkzMzhhNDZhXkEyXkFqcGdeQXVyNDE5MTU2MDE@._V1_UY268_CR1,0,182,268_AL_.jpg", Price = 3.5, ProductionYear = new DateTime(1955, 1, 1), Rating = 7.0D, TrailerUrl = "https://www.youtube.com/watch?v=G2irBCrSakE", Watched = false, Country = Country.United_States_of_America },
             new Movie() { MovieId = 34, DirectorId = 28, GenreId = 2, Title = "The Naked Gun: From the Files of Police Squad!", Duration = 85, PhotoUrl = "https://m.media-amazon.com/images/M/MV5BODk1ZWM4ZjItMjFhZi00MDMxLTgxNmYtODFhNWZlZTkwM2UwXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX182_CR0,0,182,268_AL_.jpg", Price = 3.4, ProductionYear = new DateTime(1988, 1, 1), Rating = 7.6D, TrailerUrl = "https://www.youtube.com/watch?v=PACTQutbow4", Watched = false, Country = Country.United_States_of_America },
             new Movie() { MovieId = 35, DirectorId = 29, GenreId = 1, Title = "8 Mile", Duration = 110, PhotoUrl = "https://m.media-amazon.com/images/M/MV5BOWI3MDIzZmYtN2Y3MC00YTljLWFiYmYtNWIzMjg1ZWQ1ODlhXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX182_CR0,0,182,268_AL_.jpg", Price = 7.1, ProductionYear = new DateTime(2002, 1, 1), Rating = 7.6D, TrailerUrl = "https://www.youtube.com/watch?v=axGVrfwm9L4", Watched = false, Country = Country.United_States_of_America },
             new Movie() { MovieId = 36, DirectorId = 30, GenreId = 8, Title = "Running Scared", Duration = 122, PhotoUrl = "https://m.media-amazon.com/images/M/MV5BMTIwOTAzMDc4MF5BMl5BanBnXkFtZTcwNjY5MzIzMQ@@._V1_UX182_CR0,0,182,268_AL_.jpg", Price = 9.5, ProductionYear = new DateTime(2006, 1, 1), Rating = 7.4D, TrailerUrl = "https://www.youtube.com/watch?v=D8mGXIb1Nog", Watched = false, Country = Country.United_States_of_America },
             new Movie() { MovieId = 37, DirectorId = 22, GenreId = 8, Title = "Rear Window", Duration = 112, PhotoUrl = "https://m.media-amazon.com/images/M/MV5BNGUxYWM3M2MtMGM3Mi00ZmRiLWE0NGQtZjE5ODI2OTJhNTU0XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UY268_CR0,0,182,268_AL_.jpg", Price = 12, ProductionYear = new DateTime(1954, 1, 1), Rating = 8.4D, TrailerUrl = "https://www.youtube.com/watch?v=m01YktiEZCw", Watched = false, Country = Country.United_States_of_America }
             );
        }
    }
}
